#!/usr/bin/env bash

TRASH_DIR=/tmp/.trash
TRASH_LOG="$TRASH_DIR/.log"

if [ ! -d "$TRASH_DIR" ]; then
	mkdir -p /tmp/.trash
fi

TIME=`date +"%Y-%m-%d %H:%M:%S"`

for i in $@
do
	SRC="$PWD/$i"
	if [ -e "$SRC" ]; then
		DST="$TRASH_DIR/$TIME/$SRC"
		DST_DIR=$(dirname "$DST")
		echo $SRC
		mkdir -p "$DST_DIR"
		mv "$SRC" "$DST"
		#echo "$SRC -> $DST"
		echo -e "$TIME\t$SRC" >> $TRASH_LOG
	else
		echo "$SRC not exists! pass"
	fi
done

